import type { AuthUser, Profile, Hospital, Responder, Emergency, Notification, EmergencyContact } from '../types'

export const DEMO_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-001',
    profile_id: 'prof-hospital-002',
    name: 'City General Hospital',
    license_number: 'HOSP-001-CA',
    address: '123 Main Street',
    city: 'San Francisco',
    state: 'CA',
    zip_code: '94102',
    country: 'US',
    phone: '+1 (415) 555-0100',
    email: 'emergency@citygeneral.org',
    latitude: 37.7749,
    longitude: -122.4194,
    emergency_capacity: 35,
    current_load: 12,
    accepts_ambulance: true,
    specialties: ['Level 1 Trauma Center', 'Comprehensive Stroke Center', 'Cardiology & Cath Lab', 'Pediatric ICU', 'Burn Unit'],
    is_verified: true,
    is_active: true,
    operating_hours: {
      all: '24/7 Emergency & Critical Care',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-002',
    name: 'Metro Medical Center',
    license_number: 'HOSP-002-CA',
    address: '456 Oak Avenue',
    city: 'Oakland',
    state: 'CA',
    zip_code: '94612',
    country: 'US',
    phone: '+1 (510) 555-0200',
    email: 'er@metromedical.org',
    latitude: 37.8044,
    longitude: -122.2711,
    emergency_capacity: 25,
    current_load: 6,
    accepts_ambulance: true,
    specialties: ['Emergency Medicine', 'Orthopedics', 'Stroke Care', 'Cardiac Surgery'],
    is_verified: true,
    is_active: true,
    operating_hours: {
      all: '24/7 Emergency Care',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-003',
    name: 'University Hospital & Trauma Institute',
    license_number: 'HOSP-003-CA',
    address: '789 University Drive',
    city: 'Berkeley',
    state: 'CA',
    zip_code: '94704',
    country: 'US',
    phone: '+1 (510) 555-0300',
    email: 'trauma@univhospital.org',
    latitude: 37.8719,
    longitude: -122.2585,
    emergency_capacity: 40,
    current_load: 18,
    accepts_ambulance: true,
    specialties: ['Level 1 Trauma', 'Neurosurgery', 'Organ Transplant', 'Adult & Pediatric ECMO'],
    is_verified: true,
    is_active: true,
    operating_hours: {
      all: '24/7 Emergency Care',
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_RESPONDERS: Responder[] = [
  {
    id: 'resp-001',
    profile_id: 'prof-responder-003',
    employee_id: 'EMP-MEDIC-42',
    hospital_id: 'hosp-001',
    license_number: 'PARAMEDIC-9921',
    certification_level: 'Paramedic',
    specialties: ['Advanced Cardiac Life Support', 'Trauma Triage', 'Pediatric Life Support'],
    is_available: true,
    current_latitude: 37.7712,
    current_longitude: -122.3925,
    last_location_update: new Date().toISOString(),
    shift_start: '07:00',
    shift_end: '19:00',
    vehicle_type: 'ambulance',
    vehicle_id: 'AMB-Unit-4',
    full_name: 'Marcus Miller',
    distance_km: 1.8,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: {
      full_name: 'Marcus Miller',
      phone: '+1 (555) 345-6789',
      email: 'responder@demo.com',
      avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop',
    },
  },
  {
    id: 'resp-002',
    profile_id: 'prof-resp-002',
    employee_id: 'EMP-EMT-18',
    hospital_id: 'hosp-001',
    license_number: 'EMT-A-7731',
    certification_level: 'AEMT',
    specialties: ['Pre-hospital Trauma', 'Rapid Response Transport'],
    is_available: true,
    current_latitude: 37.7812,
    current_longitude: -122.4101,
    last_location_update: new Date().toISOString(),
    shift_start: '08:00',
    shift_end: '20:00',
    vehicle_type: 'ambulance',
    vehicle_id: 'AMB-Unit-7',
    full_name: 'Sarah Jenkins',
    distance_km: 2.4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: {
      full_name: 'Sarah Jenkins',
      phone: '+1 (555) 432-8765',
      email: 's.jenkins@citygeneral.org',
      avatar_url: 'https://images.unsplash.com/photo-1594824813565-d4193582be6c?w=150&auto=format&fit=crop',
    },
  },
  {
    id: 'resp-003',
    profile_id: 'prof-resp-003',
    employee_id: 'EMP-PARAMEDIC-09',
    hospital_id: 'hosp-001',
    license_number: 'PARAMEDIC-4412',
    certification_level: 'Paramedic',
    specialties: ['Critical Care Paramedic (CCEMT-P)', 'Airway Management'],
    is_available: false,
    current_latitude: 37.7654,
    current_longitude: -122.4289,
    last_location_update: new Date().toISOString(),
    shift_start: '12:00',
    shift_end: '00:00',
    vehicle_type: 'medic_unit',
    vehicle_id: 'MEDIC-Unit-12',
    full_name: 'David Kim',
    distance_km: 3.1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: {
      full_name: 'David Kim',
      phone: '+1 (555) 789-0123',
      email: 'd.kim@citygeneral.org',
      avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop',
    },
  },
  {
    id: 'resp-004',
    profile_id: 'prof-resp-004',
    employee_id: 'EMP-RN-55',
    hospital_id: 'hosp-001',
    license_number: 'RN-C-8819',
    certification_level: 'RN',
    specialties: ['Emergency Room Flight Nurse', 'Pediatric Emergency'],
    is_available: true,
    current_latitude: 37.7889,
    current_longitude: -122.4012,
    last_location_update: new Date().toISOString(),
    shift_start: '06:00',
    shift_end: '18:00',
    vehicle_type: 'supervisor',
    vehicle_id: 'SUP-Unit-1',
    full_name: 'Lisa Wang',
    distance_km: 1.2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    profiles: {
      full_name: 'Lisa Wang',
      phone: '+1 (555) 654-3210',
      email: 'l.wang@citygeneral.org',
      avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop',
    },
  },
]

export const DEMO_USERS: Record<string, { password: string; authUser: AuthUser }> = {
  'patient@demo.com': {
    password: 'password123',
    authUser: {
      id: 'demo-patient-uuid-001',
      email: 'patient@demo.com',
      role: 'patient',
      profile: {
        id: 'prof-patient-001',
        user_id: 'demo-patient-uuid-001',
        role: 'patient',
        full_name: 'Alex Johnson',
        email: 'patient@demo.com',
        phone: '+1 (555) 234-5678',
        avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop',
        date_of_birth: '1990-05-15',
        blood_type: 'O+',
        allergies: ['Penicillin', 'Peanuts'],
        medical_conditions: ['Asthma', 'Mild Hypertension'],
        medications: ['Albuterol Inhaler (PRN)', 'Lisinopril 10mg'],
        emergency_notes: 'Carry inhaler in backpack at all times. Allergic to penicillin (rash/anaphylaxis).',
        address: '742 Evergreen Terrace',
        city: 'San Francisco',
        state: 'CA',
        zip_code: '94102',
        country: 'US',
        latitude: 37.7749,
        longitude: -122.4194,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
  },
  'hospital@demo.com': {
    password: 'password123',
    authUser: {
      id: 'demo-hospital-uuid-002',
      email: 'hospital@demo.com',
      role: 'hospital',
      profile: {
        id: 'prof-hospital-002',
        user_id: 'demo-hospital-uuid-002',
        role: 'hospital',
        full_name: 'Dr. Sarah Chen (Chief of ER)',
        email: 'hospital@demo.com',
        phone: '+1 (555) 987-6543',
        avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop',
        address: '123 Main Street',
        city: 'San Francisco',
        state: 'CA',
        zip_code: '94102',
        country: 'US',
        latitude: 37.7749,
        longitude: -122.4194,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      hospital: DEMO_HOSPITALS[0],
    },
  },
  'responder@demo.com': {
    password: 'password123',
    authUser: {
      id: 'demo-responder-uuid-003',
      email: 'responder@demo.com',
      role: 'responder',
      profile: {
        id: 'prof-responder-003',
        user_id: 'demo-responder-uuid-003',
        role: 'responder',
        full_name: 'Marcus Miller',
        email: 'responder@demo.com',
        phone: '+1 (555) 345-6789',
        avatar_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop',
        address: '456 Mission Bay Blvd',
        city: 'San Francisco',
        state: 'CA',
        zip_code: '94158',
        country: 'US',
        latitude: 37.7712,
        longitude: -122.3925,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
      responder: DEMO_RESPONDERS[0],
    },
  },
  'admin@demo.com': {
    password: 'password123',
    authUser: {
      id: 'demo-admin-uuid-004',
      email: 'admin@demo.com',
      role: 'admin',
      profile: {
        id: 'prof-admin-004',
        user_id: 'demo-admin-uuid-004',
        role: 'admin',
        full_name: 'Elena Rostova (System Admin)',
        email: 'admin@demo.com',
        phone: '+1 (555) 111-2233',
        avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop',
        address: '100 Emergency HQ Plaza',
        city: 'San Francisco',
        state: 'CA',
        zip_code: '94105',
        country: 'US',
        latitude: 37.7891,
        longitude: -122.4014,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    },
  },
}

export const INITIAL_DEMO_EMERGENCIES: Emergency[] = [
  {
    id: 'emg-demo-101',
    patient_id: 'prof-patient-001',
    hospital_id: 'hosp-001',
    responder_id: 'resp-001',
    status: 'on_the_way',
    priority: 'critical',
    chief_complaint: 'Severe Chest Pain & Shortness of Breath',
    description: '54yo patient reporting crushing sub-sternal chest pain radiating to left arm. Conscious, pale, diaphoretic. Vital signs taken on scene.',
    patient_latitude: 37.7749,
    patient_longitude: -122.4194,
    patient_address: '742 Evergreen Terrace, San Francisco, CA',
    hospital_latitude: 37.7749,
    hospital_longitude: -122.4194,
    responder_latitude: 37.7712,
    responder_longitude: -122.3925,
    estimated_arrival: new Date(Date.now() + 6 * 60000).toISOString(),
    vitals: {
      heart_rate: '118 bpm',
      blood_pressure: '148/94 mmHg',
      oxygen_saturation: '93%',
      respiratory_rate: '24 /min',
      temperature: '98.8 °F',
      glucose: '124 mg/dL',
    },
    medications_given: ['Oxygen via Nasal Cannula (4L/min)', 'Aspirin 324mg (Chewed)', 'Nitroglycerin 0.4mg SL (Dose 1)'],
    procedures_performed: ['12-Lead ECG Acquired (STEMI Alert)', 'IV Access (18G Left Antecubital)', 'Continuous Cardiac Monitoring'],
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60000).toISOString(),
    patient: {
      id: 'prof-patient-001',
      full_name: 'Alex Johnson',
      phone: '+1 (555) 234-5678',
      date_of_birth: '1972-04-12',
      blood_type: 'O+',
      allergies: ['Penicillin', 'Peanuts'],
      medical_conditions: ['Hypertension', 'Type 2 Diabetes'],
      medications: ['Lisinopril 10mg', 'Metformin 500mg'],
      emergency_notes: 'Wife Sarah Johnson is primary contact.',
    },
    hospital: DEMO_HOSPITALS[0],
    responder: DEMO_RESPONDERS[0],
  },
  {
    id: 'emg-demo-102',
    patient_id: 'prof-patient-002',
    hospital_id: 'hosp-001',
    status: 'pending',
    priority: 'high',
    chief_complaint: 'Motor Vehicle Accident with Head Injury',
    description: '2-vehicle collision at intersection. Patient has 4cm forehead laceration, momentary loss of consciousness, alert now but complaining of neck stiffness.',
    patient_latitude: 37.7833,
    patient_longitude: -122.4167,
    patient_address: 'Market St & 4th St, San Francisco, CA',
    hospital_latitude: 37.7749,
    hospital_longitude: -122.4194,
    vitals: {
      heart_rate: '94 bpm',
      blood_pressure: '132/84 mmHg',
      oxygen_saturation: '98%',
      respiratory_rate: '18 /min',
      temperature: '98.6 °F',
    },
    created_at: new Date(Date.now() - 22 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 22 * 60000).toISOString(),
    patient: {
      id: 'prof-patient-002',
      full_name: 'Michael Torres',
      phone: '+1 (555) 456-7890',
      date_of_birth: '1988-11-23',
      blood_type: 'A+',
      allergies: ['Sulfa Drugs'],
      medical_conditions: ['None reported'],
      medications: ['None'],
    },
    hospital: DEMO_HOSPITALS[0],
  },
  {
    id: 'emg-demo-103',
    patient_id: 'prof-patient-003',
    hospital_id: 'hosp-001',
    responder_id: 'resp-002',
    status: 'resolved',
    priority: 'medium',
    chief_complaint: 'Severe Allergic Reaction (Anaphylaxis Treated)',
    description: 'Bee sting reaction. Patient received EpiPen IM prior to arrival. Second dose Epinephrine administered by EMS. Patient stabilized and transferred to City General ER.',
    patient_latitude: 37.7699,
    patient_longitude: -122.4469,
    patient_address: 'Golden Gate Park Conservatory, San Francisco, CA',
    hospital_latitude: 37.7749,
    hospital_longitude: -122.4194,
    responder_latitude: 37.7812,
    responder_longitude: -122.4101,
    actual_arrival: new Date(Date.now() - 40 * 60000).toISOString(),
    resolved_at: new Date(Date.now() - 25 * 60000).toISOString(),
    vitals: {
      heart_rate: '88 bpm',
      blood_pressure: '120/80 mmHg',
      oxygen_saturation: '99%',
      respiratory_rate: '16 /min',
    },
    medications_given: ['Epinephrine 0.3mg IM', 'Diphenhydramine 50mg IV', 'Solu-Medrol 125mg IV'],
    created_at: new Date(Date.now() - 90 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 25 * 60000).toISOString(),
    patient: {
      id: 'prof-patient-003',
      full_name: 'Emma Watson',
      phone: '+1 (555) 789-3214',
      date_of_birth: '1995-08-04',
      blood_type: 'B+',
      allergies: ['Bee Venom', 'Latex'],
    },
    hospital: DEMO_HOSPITALS[0],
    responder: DEMO_RESPONDERS[1],
  },
  {
    id: 'emg-demo-104',
    patient_id: 'prof-patient-004',
    hospital_id: 'hosp-001',
    status: 'accepted',
    priority: 'high',
    chief_complaint: 'Acute Stroke Symptoms (FAST Positive)',
    description: '68yo female with sudden onset right-sided facial droop, arm weakness, and slurred speech starting 45 minutes ago. Stroke Code Activated.',
    patient_latitude: 37.7621,
    patient_longitude: -122.4355,
    patient_address: '520 Castro Street, San Francisco, CA',
    hospital_latitude: 37.7749,
    hospital_longitude: -122.4194,
    created_at: new Date(Date.now() - 8 * 60000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60000).toISOString(),
    patient: {
      id: 'prof-patient-004',
      full_name: 'Dorothy Miller',
      phone: '+1 (555) 890-1234',
      date_of_birth: '1956-02-18',
      blood_type: 'AB+',
      allergies: ['Codeine'],
    },
    hospital: DEMO_HOSPITALS[0],
  },
]

export const DEMO_CONTACTS: EmergencyContact[] = [
  {
    id: 'contact-001',
    patient_id: 'prof-patient-001',
    name: 'Sarah Johnson',
    relationship: 'Spouse',
    phone: '+1 (555) 234-9988',
    email: 'sarah.j@example.com',
    is_primary: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'contact-002',
    patient_id: 'prof-patient-001',
    name: 'Dr. Robert Davis',
    relationship: 'Primary Care Physician',
    phone: '+1 (555) 888-2121',
    email: 'dr.davis@pacificclinic.org',
    is_primary: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'contact-003',
    patient_id: 'prof-patient-001',
    name: 'Michael Johnson',
    relationship: 'Brother',
    phone: '+1 (555) 333-4455',
    email: 'mjohnson@example.com',
    is_primary: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_AUDIT_LOGS = [
  {
    id: 'log-001',
    user_id: 'demo-patient-uuid-001',
    user_email: 'patient@demo.com',
    action: 'EMERGENCY_TRIGGERED',
    resource_type: 'emergencies',
    resource_id: 'emg-demo-101',
    ip_address: '192.168.1.104',
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
    details: { chief_complaint: 'Severe Chest Pain', priority: 'critical' },
  },
  {
    id: 'log-002',
    user_id: 'demo-hospital-uuid-002',
    user_email: 'hospital@demo.com',
    action: 'EMERGENCY_ACCEPTED',
    resource_type: 'emergencies',
    resource_id: 'emg-demo-101',
    ip_address: '10.0.4.12',
    created_at: new Date(Date.now() - 12 * 60000).toISOString(),
    details: { hospital: 'City General Hospital', bed_assigned: 'Trauma Bay 2' },
  },
  {
    id: 'log-003',
    user_id: 'demo-hospital-uuid-002',
    user_email: 'hospital@demo.com',
    action: 'RESPONDER_DISPATCHED',
    resource_type: 'responders',
    resource_id: 'resp-001',
    ip_address: '10.0.4.12',
    created_at: new Date(Date.now() - 11 * 60000).toISOString(),
    details: { unit: 'AMB-Unit-4', responder: 'Marcus Miller' },
  },
  {
    id: 'log-004',
    user_id: 'demo-responder-uuid-003',
    user_email: 'responder@demo.com',
    action: 'STATUS_UPDATED',
    resource_type: 'emergencies',
    resource_id: 'emg-demo-101',
    ip_address: '172.56.21.9',
    created_at: new Date(Date.now() - 9 * 60000).toISOString(),
    details: { new_status: 'on_the_way', eta_minutes: 6 },
  },
  {
    id: 'log-005',
    user_id: 'demo-admin-uuid-004',
    user_email: 'admin@demo.com',
    action: 'SYSTEM_SETTINGS_BACKUP',
    resource_type: 'system',
    resource_id: 'sys-backup-01',
    ip_address: '10.0.1.1',
    created_at: new Date(Date.now() - 60 * 60000).toISOString(),
    details: { status: 'completed', records_verified: 148 },
  },
]

export const INITIAL_DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-demo-1',
    user_id: 'prof-patient-001',
    title: 'Ambulance En Route',
    message: 'Paramedic Marcus Miller (AMB-Unit-4) is 1.8km away and arriving in approx 6 mins.',
    type: 'responder_en_route',
    is_read: false,
    created_at: new Date(Date.now() - 4 * 60000).toISOString(),
  },
  {
    id: 'notif-demo-2',
    user_id: 'prof-patient-001',
    title: 'Emergency Request Accepted',
    message: 'City General Hospital has accepted your emergency request and prepared Trauma Bay 2.',
    type: 'emergency_accepted',
    is_read: true,
    created_at: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'notif-demo-3',
    user_id: 'prof-hospital-002',
    title: 'New Critical SOS Incoming',
    message: 'CRITICAL: Severe Chest Pain & Shortness of Breath at 742 Evergreen Terrace.',
    type: 'emergency_created',
    is_read: false,
    created_at: new Date(Date.now() - 14 * 60000).toISOString(),
  },
]

export function getDemoEmergencyById(id: string): Emergency | undefined {
  try {
    const raw = localStorage.getItem('emergency_system_emergencies')
    if (raw) {
      const list: Emergency[] = JSON.parse(raw)
      const found = list.find(e => e.id === id)
      if (found) return found
    }
  } catch (e) {
    console.warn('Could not load from localStorage:', e)
  }
  return INITIAL_DEMO_EMERGENCIES.find(e => e.id === id)
}
